<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup Condition="'$(MSBuildProjectName)' == 'RTEA'">
    <Link>
      <ProgramDatabaseFile>$(MSBuildProjectDirectory)\build-mp\multiplayer-native.pdb</ProgramDatabaseFile>
    </Link>
  </ItemDefinitionGroup>
</Project>
